### PR TITLE
Added setDisable($callback) on Action

### PR DESCRIPTION
**Pull request by Daaarkling**
Hi, I added this new functionality into Action. It allows to disable (not render) action, if given callback function will return TRUE (user may not have permission to see this action).

Hope it helps.

### CODE REVIEW

**Comment by paveljanda** [comment]
How does that differ from http://ublaboo.paveljanda.com/datagrid/row > Row condition?

You can allow/forbid some of your actions or group action rendering.

**Comment by Daaarkling** [comment]
I missed that one. But still can you give me example how to do it, forbid rendering of spesific action (only delete action for example) for specific row. Thanks.

**Comment by paveljanda** [comment]
Exactly that is in the documentation i sent you. :)

```php
$grid->allowRowsAction('delete', function($item) {
	return $item->id != 3;
});
```

**Comment by Daaarkling** [comment]
Great thx. I just didn't see that. Ignore my PR then :-)

**Pull request closed without merging**
