### PR TITLE
Set filters in seperate rows

### PR DESCRIPTION
**Pull request by dakorpar**
Input fielters should have their own row IMHO.
before: 
before

after: 
after

Also this is first step for successfully resolving issue https://github.com/ublaboo/datagrid/issues/270
but it's standalone feature as well so I'm creating PR only for it.

### CODE REVIEW

**Comment by dakorpar** [comment]
I added this commit https://github.com/ublaboo/datagrid/pull/324/commits/831609321c0885896369e26f0d93e4603390f5eb after  although I didn't find usages of header  snippet in serverside code, thought maybe someone else is using it in their own code for some custom thing, with this code now it should be backward compatible.

**Comment by juniwalk** [comment]
@paveljanda What do you think about this?

**Comment by paveljanda** [comment]
@juniwalk If the template is altered correctly - sure, why not.

**Comment by juniwalk** [comment]
@paveljanda Well I'm not sure if it is. You had some concerns about input focus in #270 so you should probably check it first.

**Comment by dakorpar** [comment]
@juniwalk it's not affected by this, since this does not redraw anything, and filters would be redrawed only like they were till now. This would actually make it possible to redraw header row/ filter row seperatelly later, but no code for this now.

**Comment by juniwalk** [comment]
@dakorpar I see, please fix indentation (spaces to tabs).

**Pull request closed without merging**
