### PR TITLE
Fixed problem with filters

### PR DESCRIPTION
**Pull request by juniwalk**
Trying to assign value from persistent holder to uninitialized filter.

### CODE REVIEW

**Comment by paveljanda** [comment]
Thanks.

**Comment by juniwalk** [comment]
Looks like this bug was there because I switched o5/grido to your datagrid and grido probably uses same scheme for "filters". Explains why I saw the problem immediately after installing the datagrid.

**Comment by paveljanda** [comment]
Yes. This error occurred also when you did some filtering and then removed a used filter from grid.

**Comment by juniwalk** [comment]
Oh I see, did I fix it properly then?

**Comment by paveljanda** [comment]
Almost yes. :)

There still remains the value in session, I didn't notice that before - thanks again. I don't know if it is a good idea to unset it.

... Yes, it should not be there. You may create a new filter with different values to select. Then the session value won't be in current select range.

I will implement that immediately and release version 1.0.4.

**Comment by juniwalk** [comment]
Alright :) I am having another issue with tree rendering, I will debug it and report to you back later.

**Comment by JakubKontra** [comment]
Is that bug about nodes moving?

**Comment by juniwalk** [comment]
@JakubKontra It tries to read `has_children` value from my entity as if it was array, which of course fails horribly.

**Comment by paveljanda** [comment]
That should not happen. The only place, where it is reading that property is the tree view template on line 16 and there is a check whether given item is an object or an array:

```php
{var $has_children = is_object($item) ? $item->{$tree_view_has_children_column} : $item[$tree_view_has_children_column]}
```

**Comment by juniwalk** [comment]
I am aware of that, I saw it in tracy report, trange thing is, I just tried it again and it works. :D

**Pull request merged**
