### PR TITLE
Add option to set render condition callback on action

### PR DESCRIPTION
**Pull request by jankonas**
Just like you can set render condition for item detail action, you should be able to set render condition for other actions.

### CODE REVIEW

**Comment by paveljanda** [comment]
@jankonas Thank you for the idea, I like it. Just a small note aside: Do you think you can put some functionality to a trait so the code won't be repeated across multiple classes? :)

**Comment by jankonas** [comment]
Sure, I'll try to find some time in this week to do this.

**Comment by jankonas** [comment]
I updated the PR with added trait. Sorry for the delay :-)

**Comment by paveljanda** [comment]
@jankonas Awesome. Thanks, man.

**Pull request merged**
