### PR TITLE
Unnecessary check if class exists

### PR DESCRIPTION
**Pull request by MartkCz**

### CODE REVIEW

**Comment by paveljanda** [comment]
Why is it necessary? The namespaces does not have to exist if I am not using them..

**Comment by MartkCz** [comment]
Autoloder is called every time you use class* functions, reflection methods, instanceof and more. Instanceof does not cause error if class name not exists.

**Comment by paveljanda** [comment]
Oh sure, i thought there already isn't the class_exists command. Thanks for PR.

**Comment by paveljanda** [comment]
Can you please rosolve conflicta with master? Thanks.

I remember now why there were these class exiats statements. Because of points in Scrutinizer. :) The performance metter has bigger priority though.

**Comment by MartkCz** [comment]
It's now ok?

**Comment by paveljanda** [comment]
Thanks!

**Pull request merged**
