### PR TITLE
Add possibility to create group action input box..

### PR DESCRIPTION
**Pull request by Attanon**
I want to add group actions with input box. For group changes for example prices. Please review this and comment.

### CODE REVIEW

**Comment by Attanon** [comment]
I change it little bit. No it has no BC breaks.

**Comment by Attanon** [comment]
?

**Comment by paveljanda** [comment]
Thanks, I will at it tomorrow and let you know. So far i like that.

**Comment by paveljanda** [comment]
@Attanon Can you please remove the `@deprecated` annotation? I think there can be an alias that won't throw an exception.

**Comment by Attanon** [comment]
Changed

**Pull request merged**
