### PR TITLE
Always show column with checkboxes when group actions is defined.

### PR DESCRIPTION
**Pull request by proki**
Fixed issue #472

### CODE REVIEW

**Comment by juniwalk** [comment]
@proki Hey, is it necessary to call `$control->hasGroupActions()` all the time? Calling method is slower than comparing variable.

**Comment by proki** [comment]
My mistake, I fixed it :)

**Comment by juniwalk** [comment]
Great, now just resolve the conflicts :)

**Comment by proki** [comment]
Resolved.

**Comment by juniwalk** [comment]
Thanks!

**Pull request merged**
