### PR TITLE
Set default value to filter input if filter value was set

### PR DESCRIPTION
**Pull request by dakorpar**
When some value is set to some filter in code that value should be shown in input as well

### CODE REVIEW

**Comment by juniwalk** [comment]
@dakorpar Hello, this is not done already? My filters do have default values in them.

**Comment by dakorpar** [comment]
@juniwalk not if you set this bye code with 
`$filter->setValue('value');`
then input field in html did not have value attribute set

**Comment by paveljanda** [comment]
Great idea, I like it!

**Comment by paveljanda** [comment]
Actually there is another method for this purpose: `::setDefaultFilter`

**Pull request merged**
