### PR TITLE
Update datagrid.latte

### PR DESCRIPTION
**Pull request by dkocian**
In Firefox that caused a problem with displaying border around <tr n:block="header-column-row">

### CODE REVIEW

**Comment by juniwalk** [comment]
Hello, I think that rowspan is there because of inline filters. Did you make sure there is no problem with your code?

**Comment by dkocian** [comment]
Hello, I forgot the inline filters. I've put the rowspan=2 in the condition to appear only when it's active. Always display rowspan=2 is an error. You can check in the Firefox at https://ublaboo.org/datagrid/group-action between the header and the first line missing the margin. In Chrome this works fine in both case.

**Comment by juniwalk** [comment]
You can you [n:attr](https://latte.nette.org/en/macros#toc-n-attr) for conditioned attributes, it should be better.

**Comment by juniwalk** [comment]
Have you tested it? Does it work as expected?:)

**Comment by dkocian** [comment]
Yes. It looks alright.

**Comment by paveljanda** [comment]
Cool, thanks!

**Pull request merged**
