### PR TITLE
Unit tests for DoctrineCollectionDataSource

### PR DESCRIPTION
**Pull request by dakorpar**
Unit tests for DoctrineCollectionDataSource
edit: everything is ok, tests are passing...

### CODE REVIEW

**Comment by juniwalk** [comment]
Do you need assistance?

**Comment by dakorpar** [comment]
@juniwalk I thought its not passing but that was because I started from wrong branch :) when i pushed and see number of changes I realized it. Everything is ok herr, you can check initialization if you like, but I'm preety sure this is ready for @paveljanda to merge

**Comment by juniwalk** [comment]
@dakorpar Looks ok :)

**Comment by paveljanda** [comment]
Thanks a lot!

**Pull request merged**
