### PR TITLE
Adding support nextras traversing expression

### PR DESCRIPTION
**Pull request by attreid**
Adding support nextras traversing expression to all methods except applyFilterText and apply filterMultiSelect

### CODE REVIEW

**Comment by paveljanda** [comment]
Why not these two?

I can not test that datasource, so can you add tests, that will test the whole nextras datasource?

**Comment by attreid** [comment]
applyFilterText and filterMultiSelect needs 'OR' in mysql query and Nextras dbalCollection does not support 'OR' in findBy method

I will add tests

**Comment by paveljanda** [comment]
Can you please resolve conflicts with ublaboo master branch? Thanks.

**Comment by attreid** [comment]
Nextras Orm doesn't support sqlite, so is possible to add mysql testing database?

**Comment by paveljanda** [comment]
Ok, i will add mysql database to travis.yml.

**Comment by attreid** [comment]
So, how is it going?

**Comment by dakorpar** [comment]
maybe better to use mockery for unit testing then adding database, tests should be easy to set up and fast...

**Comment by attreid** [comment]
ok, which mockery do you prefer?

**Comment by dakorpar** [comment]
it's up to @paveljanda but I believe Mockery is already there...

**Comment by paveljanda** [comment]
I have merged this PR, but can you please sum up, what happend in all these commits? Thaks!

**Comment by paveljanda** [comment]
Aren't there any BC breaks within NextrasDataSource?

**Comment by attreid** [comment]
There aren't any BC break. I only added support to write column in traversing format, except applyFilterText and applyFilterMultiSelect, because these methods needs 'OR' in mysql query and Nextras dbalCollection does not support 'OR' in findBy method.

**Comment by paveljanda** [comment]
Great, thanks!

**Comment by attreid** [comment]
When do you add this to stable version? I would like to add this repo to my projects instead of my fork

**Comment by paveljanda** [comment]
I will do that right away.

**Comment by attreid** [comment]
Thanks!

**Pull request merged**
