### PR TITLE
Hide group action checkboxes and selectbox if group action is not all…

### PR DESCRIPTION
**Pull request by dakorpar**
animation
 
With this fix is just -> 
screenshot_2

### CODE REVIEW

**Comment by paveljanda** [comment]
Can you please make both `TRUE` and `FALSE` constants uppercase?

**Comment by dakorpar** [comment]
Yes, sorry :)

**Comment by dakorpar** [comment]
ignore last two commits, it should be another pull request, but  I accidentelly created new branch from origin/master instead of ublaboo/master. I did it wrong when doing this  thing in master in first place...

**Comment by paveljanda** [comment]
Ehh. Can you please squash these commits into one?

**Pull request closed without merging**
