### PR TITLE
fix of ajax response

### PR DESCRIPTION
**Pull request by chapcz**
in my usage this fixes problem https://github.com/ublaboo/datagrid/issues/519

### CODE REVIEW

**Comment by chapcz** [comment]
I think that it was collison of snippet and block

**Comment by juniwalk** [comment]
Alright, lets get it in and see. @radekdostal test it out please :)

**Comment by radekdostal** [comment]
@juniwalk Yes, this PR fixes https://github.com/ublaboo/datagrid/issues/519. Great!

**Comment by juniwalk** [comment]
Great! Thank you @chapcz

**Pull request merged**
