### PR TITLE
Disable column translating

### PR DESCRIPTION
**Pull request by schneidermichal**

### CODE REVIEW

**Comment by paveljanda** [comment]
@schneidermichal Great idea, can you provide some tests please?

**Comment by schneidermichal** [comment]
@paveljanda I'll try it ;-)

**Comment by schneidermichal** [comment]
@paveljanda Unfortunately, I don't know how to test column header rendering...

**Comment by paveljanda** [comment]
@schneidermichal Just one last thing: it is all about column header localization, co can you name the methods and properties more like `setTranslatableHeader()` and `$translatable_header`?

**Comment by paveljanda** [comment]
Perfect, thanks!

**Pull request merged**
