### PR TITLE
Add parent Nette\Object

### PR DESCRIPTION
**Pull request by romanmatyus**
Fix for this error:
snimka obrazovky z 2016-04-06 18 14 32

### CODE REVIEW

**Comment by JakubKontra** [comment]
For me, this dependence is unnecessary.  @paveljanda ?

**Comment by paveljanda** [comment]
I agree.

But how did you came to this bluescreen?

**Comment by romanmatyus** [comment]
Variable `ItemDetail::$template` is [protected](http://ublaboo.paveljanda.com/api/datagrid/source-class-Ublaboo.DataGrid.Column.ItemDetail.html#30). Class has [method](http://ublaboo.paveljanda.com/api/datagrid/source-class-Ublaboo.DataGrid.Column.ItemDetail.html#245-252) `getTemplate()`, but latte template use it [directly](https://github.com/ublaboo/datagrid/blob/master/src/templates/datagrid.latte#L245), without this getter.

Alternate fix is (probably, I not test it) change template from
```latte
{include $items_detail->template, item => $item}
```
to
```latte
{include $items_detail->getTemplate(), item => $item}
```

**Comment by romanmatyus** [comment]
Then, what now? Now, when I compose new version of app, before deploy I manually fix it. Really I have to fork this super addon and using own version for this little bug? :)
Thanks for best Nette grid ;)

**Comment by JakubKontra** [comment]
@romanmatyus ...  @paveljanda asked you to describe "But how did you came to this bluescreen?" and you didn't answer.

**Comment by romanmatyus** [comment]
@JakubKontra I added lines of code generating this error with two ways for fix it. But ok, I go prepare the demo with this error :)

**Comment by romanmatyus** [comment]
@JakubKontra Here is [demonstration project](https://github.com/romanmatyus/web-project).
Clone, composer install, click to detail, show `/log/... . html`

**Comment by paveljanda** [comment]
I changed the template from:

```
$items_detail->template
```
to:
```
$items_detail->getTemplate()
```

Thanks for reaction

**Comment by paveljanda** [comment]
Viz https://github.com/ublaboo/datagrid/commit/5e03c591684c622ae31d02e886cbb6ecd83efbab

**Comment by romanmatyus** [comment]
Thank you!!

**Pull request closed without merging**
