### PR TITLE
Improved MultiSelect filter in Doctrine datasource

### LINKED ISSUE #295: FilterMultiSelect: Invalid condition building for Doctrine?
Hi,
I just wanted to ask, shouldn't the condition for MultiSelect in Doctrine data source be build something like this?

```php
$qb->andWhere($qb->expr()->in('o.status', ':status'))
	->setParameter('status', $values);
```

Current implementation is problematic for string values.
```
[Semantical Error] line 0, col 115 near 'active OR o.status': Error: 'active' is not defined.
```

### PR DESCRIPTION
**Pull request by juniwalk**
@paveljanda Well check it out, if there is something you don't like just let me know. It is not tested yet.

Closes #295

### CODE REVIEW

**Comment by juniwalk** [comment]
Well in my today's work it works as expected.

**Comment by paveljanda** [comment]
The checkAliases method should be used. It checks possible table aliases.

**Comment by juniwalk** [comment]
@paveljanda I know, it is there :) Line 243.

**Comment by paveljanda** [comment]
Wtf I was looking at?
Thanks, i will test it.

**Comment by juniwalk** [comment]
@paveljanda It happends :) Thanks!

**Pull request merged**
