### PR TITLE
WIP: Implemented row callback

### LINKED ISSUE #72: DataGrid: Add callback executed on row render
If I would like to color rows with banned users in red, there is currently no way to add callback that would handle this.

### PR DESCRIPTION
**Pull request by juniwalk**
Closes #72

### CODE REVIEW

**Comment by juniwalk** [comment]
I will add tests tomorrow. :)

**Comment by paveljanda** [comment]
What about other `tr` element attributes? Once you are using `Html::el`, it should be used properly, not just it's class.

Hmmm, I have to think about it.

**Comment by juniwalk** [comment]
Usage can be extended anytime, I wanted to focus on the class modification for now.

**Comment by juniwalk** [comment]
@paveljanda Shall I change the use of html control in any way?

**Comment by paveljanda** [comment]
No, that won't be that easy. That solution is fine.

Can you just change the method `Row::getClass()` to `Row::getControlClass()`?

**Comment by juniwalk** [comment]
@paveljanda  Alright, done.

**Comment by paveljanda** [comment]
When hideable columns are ready, a will release a new version. This will be in that version.

**Comment by juniwalk** [comment]
Alright :) If you need any help with modding this, let me know.

**Pull request merged**
