### PR TITLE
Fixed count after data filtering

### PR DESCRIPTION
**Pull request by sallyx**
ArrayDataSource returned the same count for filtered and nofiltered
data.
This commit fixes it by changing count after filtering.

### CODE REVIEW

**Comment by juniwalk** [comment]
Hi, could you fix coding style? Add empty spaces between the count call. Thanks.

**Comment by sallyx** [comment]
You ment ...around the count call. I have done more changes thought.

**Comment by juniwalk** [comment]
@sallyx Sorry I don't like it this way. You call count too many times unnecessarily. You just need to call count on data when the data is being outputted to datagrid.

Check how [DoctrineCollectionDataSource](https://github.com/ublaboo/datagrid/blob/v5.x/src/DataSource/DoctrineCollectionDataSource.php#L68) deals with this.

**Comment by sallyx** [comment]
Done.

**Comment by juniwalk** [comment]
Sorry for being picky, but that private data setter is not really necessary, is it?

**Comment by sallyx** [comment]
Its not necessary, but Its a good place for testing and/or debugging. It would make more sense as protected, but I don't like the idea fixing bug and changing API in one commit. 
So, If you accept this request, the next step would be make it protected.

**Comment by juniwalk** [comment]
@paveljanda What is your point of view on this?

**Comment by paveljanda** [comment]
@sallyx Can you please wrote tests for the array data source, where the previous version is broken and your changes passes? Thanks!

I would remove the `setData` mathod too. It does not bring any enhancement.

**Comment by sallyx** [comment]
The method helped me find out, how many times the data is set compared to getCount(). It was a real enhancement to have this function.
Beside debuging and testing purposes, it also help  with [separation between intention and implementation](https://martinfowler.com/bliki/FunctionLength.html).

**Comment by sallyx** [comment]
Any progress here?

**Comment by suplere** [comment]
A nestačí jen úprava ve funkci public function filter(array $filters), kde před return $this; dát 

**$this->count = sizeof($this->data);**

**Comment by paveljanda** [comment]
Tests added, fix is done. If it is more readable for you with the `setData()` method, why not.

Thanks for the work. :)

**Pull request merged**
