### PR TITLE
Support for DateTimeImmutable

### PR DESCRIPTION
**Pull request by FVesely**

### CODE REVIEW

**Comment by paveljanda** [comment]
@FVesely Thank you!

**Comment by juniwalk** [comment]
@FVesely Wrong branch probably. master is future 6.0 version.

**Comment by FVesely** [comment]
@juniwalk Ouch, sorry, what now? Should I create a new PR to v5.x branch and another PR to revert this?

**Comment by juniwalk** [comment]
@FVesely No, don't revert it, just backport it to v5.x, that's all :)

**Pull request merged**
