### PR TITLE
Fixed: Filter Date Range

### PR DESCRIPTION
**Pull request by JanGalek**
variable $conditions didnt exists. So it return error.

### CODE REVIEW

**Comment by paveljanda** [comment]
Holy crap

Thanks

**Comment by JanGalek** [comment]
sorry, in applyFilterRange its same problem. Have I PR ?

**Comment by paveljanda** [comment]
I will fix it in the evening. And also the master branch. So it's ok, thanks. :)

**Comment by JanGalek** [comment]
ok, no problem, I thanks ;)

**Pull request merged**
