### PR TITLE
Prevent "maximum call stack size exceeded" if form is submited over autosubmit

### PR DESCRIPTION
**Pull request by Ivorius**

### CODE REVIEW

**Comment by paveljanda** [comment]
Thanks you!

**Comment by paveljanda** [comment]
@Ivorius What that causes is error in submitting form via nette ajax. Any idea how to fix that?

**Comment by paveljanda** [comment]
@Ivorius What about `$this.closest('form').first()`?

**Comment by Ivorius** [comment]
@paveljanda It is same like ` $this.closest('form')` 

`
jquery.js:1406 Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Function.Sizzle.matchesSelector (http://unio.local/assets/js/admin.js:1532:14)
    at Function.jQuery.filter (http://unio.local/assets/js/admin.js:2797:15)
    at winnow (http://unio.local/assets/js/admin.js:2778:18)
    at jQuery.fn.init.is (http://unio.local/assets/js/admin.js:2836:12)
    at nette.ajax (http://unio.local/assets/js/admin.js:22992:17)
    at HTMLFormElement.requestHandler (http://unio.local/assets/js/admin.js:22874:25)
    at HTMLFormElement.dispatch (http://unio.local/assets/js/admin.js:4561:9)
    at HTMLFormElement.elemData.handle (http://unio.local/assets/js/admin.js:4247:28)
`

or 

`Uncaught RangeError: Maximum call stack size exceeded
    at Function.isPlainObject (jquery.js:273)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:218)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:228)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:228)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:228)
    at ajaxExtend (jquery.js:7655)
    at Function.ajaxSetup (jquery.js:7895)
    at Function.ajax (jquery.js:7931)
    at nette.ajax (nette.ajax.js:225)
    at HTMLFormElement.requestHandler (nette.ajax.js:48)

isPlainObject	@	jquery.js:273
jQuery.extend.jQuery.fn.extend	@	jquery.js:218
jQuery.extend.jQuery.fn.extend	@	jquery.js:228
jQuery.extend.jQuery.fn.extend	@	jquery.js:228
jQuery.extend.jQuery.fn.extend	@	jquery.js:228
ajaxExtend	@	jquery.js:7655
ajaxSetup	@	jquery.js:7895
ajax	@	jquery.js:7931
ajax	@	nette.ajax.js:225
requestHandler	@	nette.ajax.js:48
dispatch	@	jquery.js:4435
elemData.handle	@	jquery.js:4121
trigger	@	jquery.js:4350
triggerHandler	@	jquery.js:4907
before	@	nette.ajax.js:318
(anonymous)	@	nette.ajax.js:42
each	@	jquery.js:382
fire	@	nette.ajax.js:40
settings.beforeSend	@	nette.ajax.js:215
ajax	@	jquery.js:8131
ajax	@	nette.ajax.js:225
requestHandler	@	nette.ajax.js:48
dispatch	@	jquery.js:4435
elemData.handle	@	jquery.js:4121
trigger	@	jquery.js:4350
triggerHandler	@	jquery.js:4907
before	@	nette.ajax.js:318
(anonymous)	@	nette.ajax.js:42
each	@	jquery.js:382
fire	@	nette.ajax.js:40
settings.beforeSend	@	nette.ajax.js:215
ajax	@	jquery.js:8131
ajax	@	nette.ajax.js:225
requestHandler	@	nette.ajax.js:48
dispatch	@	jquery.js:4435
elemData.handle	@	jquery.js:4121
trigger	@	jquery.js:4350
triggerHandler	@	jquery.js:4907
before	@	nette.ajax.js:318
(anonymous)	@	nette.ajax.js:42
.........
`

Maybe some problem with webpack?

**Comment by Ivorius** [comment]
After first load page (F5 reload) - change select box - ajax request and load new data - everything is ok.  But after second change select, it throws errors.

**Comment by paveljanda** [comment]
@Ivorius Do you have a working patch, that would not break nette.ajax.js beahviour and fix the "Maximum call stack size exceeded" at same time?

**Comment by Ivorius** [comment]
Webpack is not problem. 
I tried classic approach
```
<script src="{$basePath}/assets/test/jquery.min.js"></script>
<script src="{$basePath}/assets/test/netteForms.js"></script>
<script src="{$basePath}/assets/test/nette.ajax.js"></script>
<script src="{$basePath}/assets/test/datagrid.js"></script>
<script>
    $.nette.init();
</script> 
```
and I have still same problem with 

> maximum call stack size exceeded

**Comment by Ivorius** [comment]
Hm, I tried your assets from http://ublaboo.org/datagrid/ 
```
		<script src="/assets/compiled/libraries.js?v=2016-11-09"></script>
		<script src="/assets/compiled/app.js?v=2016-11-09"></script>
		<script>
			$.nette.init();
		</script>
```
and everythink work. Which version do you use for libraries?

**Comment by Ivorius** [comment]
Solved! nette.ajax.js infinitive loop bug with nette 2.3 - https://github.com/vojtech-dobes/nette.ajax.js/pull/135/commits/22264895980f13229c8f14a97862604690347836

**Comment by juniwalk** [comment]
@Ivorius Yeah that bug is starting to be real pain in the ...

**Comment by paveljanda** [comment]
... ASS.

Could somebody force them to merge the PR?

**Comment by dakorpar** [comment]
I'm afraid nette.ajax is dead, no activity there at all, which is huge problem because it's used in most nette projects as well...

**Comment by paveljanda** [comment]
@dakorpar I will try somebody on gitter. It can not be dead, as you said, 90% of nette projects are using it.

**Comment by juniwalk** [comment]
@paveljanda If @vojtech-dobes does not have time to take care of it he should probably get some more maintainers to help him as the rate of updates is really bad :X

**Comment by paveljanda** [comment]
@juniwalk :D Now I understand the people leaving Nette.

I will throw that topic into the nette crowd at upcomming PoSobota event.

**Comment by dakorpar** [comment]
@paveljanda anything about nette.ajax.js news maybe? Will someone fork that and maintain?
IMHO it should be part of nette framework

**Comment by paveljanda** [comment]
@dakorpar Indeed. Come & join david grud on PoSobota and talk him into that.

**Comment by dakorpar** [comment]
I'm afraid it's to far for me, I'm from Croatia and probably they're talking Czech which is foreign for me...
I will come to Prague this year, but in begining of september.

**Pull request merged**
