### PR TITLE
DataGrid: Make the table stripped (colored even rows)

### PR DESCRIPTION
**Pull request by juniwalk**

### CODE REVIEW

**Comment by paveljanda** [comment]
I had it there, but have to remove.. Do you know what will happen if you are using item detail? :)

**Comment by juniwalk** [comment]
Hmm, what will happen? Maybe add `$grid->addClass('table-striped');` then?

**Comment by paveljanda** [comment]
You can try that yourself. :) The striped-schema breaks. Item detail has to be loaded into another row (`<table>/<tbody>` can not have some other children than <tr>) and that will switch all remaining event <-> odd table rows color schema.

**Comment by paveljanda** [comment]
Maybe there is a solution although not so nice. Item detail can be loaded into 2 table rows.  The second will stay empty/hidden/whatever. Just to let the striped color schema work.

**Comment by paveljanda** [comment]
I will look at it.

**Comment by juniwalk** [comment]
Alright, I will look into it once I've got some spare time.

**Comment by paveljanda** [comment]
DataGrid is now by-default "striped", table class can be chaged in {block #table-class} when extending parent template

**Comment by juniwalk** [comment]
I've noticed, great work! :)

**Pull request closed without merging**
