### PR TITLE
Fix sorting by date

### PR DESCRIPTION
**Pull request by schneidermichal**

### CODE REVIEW

**Comment by juniwalk** [comment]
@schneidermichal Hello, could you please use `instanceof` instead of `is_a` function?

**Comment by paveljanda** [comment]
@schneidermichal Could you please squash these commits? Thanks!

**Comment by schneidermichal** [comment]
Done. I'm sorry.

**Comment by paveljanda** [comment]
@schneidermichal Could you please squash these commits? Thanks!

**Comment by juniwalk** [comment]
@paveljanda You should be able to squash them when merging! :) Click the arrow!

**Comment by dakorpar** [comment]
That should save us a lot of troubles, many times when doing force push PR automatically closes.

**Comment by paveljanda** [comment]
@dakorpar Never happend to me.

**Comment by paveljanda** [comment]
@schneidermichal Thank you.

**Comment by dakorpar** [comment]
@paveljanda maybe doesn't happen to owners of repository.
I'll check my PR I think in few of them actually wroted PR closed because of push --force

**Comment by juniwalk** [comment]
@dakorpar I have been force pushing to PRs to this repository multiple times, never closed on me.

**Comment by paveljanda** [comment]
@dakorpar Never happened to me when updating pull requests (Not my repos). You can "google" some tutorial on youtube.

**Comment by schneidermichal** [comment]
I made the fix directly to master branch, as I found, making feature branch would be better...

**Comment by dakorpar** [comment]
well there's not much there you either squash them with rebase -i and hash of first commit you want to take and force push, or you can do it git reset --soft hash, so I don't really see what could go wrong and why PR was automatically closed... Could be something with my setup or something... Maybe I went one commit to far...

**Pull request merged**
