### PR TITLE
Fixed support of dibi 2.x.

### PR DESCRIPTION
**Pull request by radekdostal**
This PR fixes "DataGrid can not take [DibiFluent] as data source" exception, if dibi 2.x is used.

### CODE REVIEW

**Comment by juniwalk** [comment]
Wouldn't this broke support for Dibi 3.0? I don't know what @paveljanda had in mind for dibi.

Better way would be to add it as OR to take both options, like that:

```php
} else if (is_array($source)) {
	$source = new DataSource\ArrayDataSource($source);
 
} else if ($source instanceof Dibi\Fluent || $source instanceof DibiFluent) {
	$driver = $source->getConnection()->getDriver();

	if ($driver instanceof Dibi\Drivers\OdbcDriver) {
```

**Comment by paveljanda** [comment]
@juniwalk I would use the `OR`. It is the best options. We sure should support Dibi 3 and 2

**Comment by radekdostal** [comment]
Dibi 3 defines class alias DibiFluent for Dibi\Fluent.

**Comment by juniwalk** [comment]
@radekdostal But we can't be sure it will be there forever.

**Comment by radekdostal** [comment]
@juniwalk It is a question for @dg, if at least dibi 3.x will be compatible with dibi 2.x.

**Comment by dakorpar** [comment]
IMHO if Dibi drops support datagrid should also...
If someone has to use old version of dibi, then he also has to use older version of datagrid...
It's good to support till some time, but I don't see much sense in supporting old obsolete libraries...

**Comment by paveljanda** [comment]
@dakorpar aarkling Dibi 2.x is not obsolete

**Comment by juniwalk** [comment]
@paveljanda Well, [it is obsolete](https://github.com/dg/dibi/releases/tag/v2.3.5) but it is used in many projects :)

**Comment by juniwalk** [comment]
@radekdostal Please, use the `OR` on that alias and it will be merged. However, Dibi 2.x support will be dropped in Datagrid 6.x

**Comment by radekdostal** [comment]
I am sorry for the new PR, but I have deleted the corresponding branch.
See https://github.com/ublaboo/datagrid/pull/480.

**Pull request closed without merging**
