### PR TITLE
Fix issue #395

### PR DESCRIPTION
**Pull request by attreid**
Fixed datagrid.coffee

### CODE REVIEW

**Comment by paveljanda** [comment]
I am sure the fix does not need 500 lines of JS to be changed.. Please just send the .coffe, i will build the remaining assets.

**Comment by juniwalk** [comment]
@paveljanda Sorry, I told him to compile JS too.

**Comment by attreid** [comment]
JS reverted

**Comment by paveljanda** [comment]
@juniwalk A also thought this is a great idea. A do not now.
Maybe I should add some gulpfile into assets dir.

**Pull request merged**
